import 'package:get/get.dart';

List strings = [
  'Əsas səhifə',
  'Kateqoriyalar',
  'Videolar',
  'Seçilmişlər'
];

class LocaleString extends Translations {
@override
Map<String, Map<String, String>> get keys => {
'en_EN': {
  'Əsas səhifə':'Homepage',
  'Kateqoriyalar':'Categories',
  'Videolar':'Videos',
  'Seçilmişlər':'Bookmarks',
  'Axtarış sözünüzü yazın...':'Type your search term...',
  'Axtarış üçün açar sözlər qeyd edin...': 'Type keyword for searching...',
  'Sil': 'Delete',
  'Heç bir nəticə tapılmadı.':'No results found.',
  'Şəkli görmək üçün üzərinə klikləyin':'Click on the image to view it',
  'Xəbər seçilmişlərdən çıxarıldı.':'The news was removed from the bookmarks.',
  'Xəbər seçilmişlərə əlavə edildi.':'The news has been added to bookmarks',
  'Kateqoriya: ':'Category: ',
  'Hal-hazırda heç bir xəbəri seçilmişlərə əlavə etməmisiniz.':'You have not added any news to bookmarks at this time.',
  'Seçilmiş xəbəri "Seçilmişlər" bölümündən çıxartmaq üçün sola doğru sürüşdürün':'Swipe left to remove the selected news from the "Bookmarks" section',
  'Göstəriləcək başqa xəbər yoxdur.':'There is no other news to display.',
  'Görünüm':'Appearance',
  'Qaranlıq rejim':'Darkmode',
  'Qənaət rejimi':'Data savings mode',
  'Yazı ölçüsü':'Text size',
  'Tətbiq dili':'Language',
  'Bildirişlər':'Notifications',
  'Son dəqiqə xəbərləri üzrə bildirişlər':'Notifications about breaking news',
  'Xüsusi günlərlə bağlı bildirişlər':'Notices about special days',
  'Proqram haqqında':'About app',
  'Müəllif':'Author',
  'Qurucu şirkət':'Company',
  'Paramterlər': 'Settings',
  'Vayuta məzənnəsi':'Currency',
  'Hava haqqında':'Weather',
  'Haqqımızda':'About us',
  'Bizimlə əlaqə':'Contact us',
  'Mesaj göndərin':'Send message',
  'Bizi qiymətləndirin':'Rate us',
  'Məlumatların bazadan çəkilməsi zamanı xəta baş verdi.':'An error occurred while retrieving data from the database.',
  'Məlumat panoya kopyalandı.':'The information has been copied to the clipboard.',
  'Əlaqə telefonu':'Contact phone',
  'Elektron poçt':'Email',
  'Ünvan':'Address',
  'İş günləri və saatları':'Working days and hours',
  'Sosial şəbəkələr':'Social networks',
  'Onlayn mesaj göndərin':'Send online message',
  'Əlavə sual və təkliflərinizlə bağlı aşağıdakı formdan bizə yaza bilərsiniz. Ən qısa zamanda əməkdaşlarımız sizə geri dönüş edəcəklər.':'You can write to us about your additional questions and suggestions using the form below. Our employees will get back to you as soon as possible.',
  'Ad və soyadınız':'Name and surname',
  'Ad və soyadınızı qeyd etməmisiniz.':'Name and surname are required',
  'Email':'Email',
  'Email qeyd etməmisiniz.':'Email is required.',
  'Mesajınız':'Your message',
  'Heç bir mesaj qeyd etməmisiniz.':'You have not added any messages.',
  'Göndər':'Send',
  'Tətbiq daxili xəta baş verdi.':'An internal application error has occurred.',
},
'tr_TR': {
  'Əsas səhifə':'Anasayfa',
  'Kateqoriyalar':'Kategoriler',
  'Videolar':'Videolar',
  'Seçilmişlər':'Seçilmişler',
  'Axtarış sözünüzü yazın...':'Arama kelimenizi yazın...',
  'Axtarış üçün açar sözlər qeyd edin...': 'Arama için anahtar kelimeler belirtin...',
  'Sil': 'Sil',
  'Heç bir nəticə tapılmadı.':'Hiç bir sonuç bulunamadı.',
  'Şəkli görmək üçün üzərinə klikləyin':'Resmi görmek için tıklayın',
  'Xəbər seçilmişlərdən çıxarıldı.':'Haber seçilmişlerden çıkartıldı.',
  'Xəbər seçilmişlərə əlavə edildi.':'Haber "Seçilmişler" bölümüne eklendi.',
  'Kateqoriya: ':'Kategori: ',
  'Hal-hazırda heç bir xəbəri seçilmişlərə əlavə etməmisiniz.':'Şu anda seçilmişlere herhangi bir haber eklemediniz.',
  'Seçilmiş xəbəri "Seçilmişlər" bölümündən çıxartmaq üçün sola doğru sürüşdürün':'"Seçilmişler" bölümünden seçilen haberleri kaldırmak için sola kaydırın',
  'Göstəriləcək başqa xəbər yoxdur.':'Görüntülenecek başka haber yok.',
  'Görünüm':'Görünüş',
  'Qaranlıq rejim':'Karanlık mod',
  'Qənaət rejimi':'Tasarruf modu',
  'Yazı ölçüsü':'Yazı boyutu',
  'Tətbiq dili':'Uygulama dili',
  'Bildirişlər':'Bildirimler',
  'Son dəqiqə xəbərləri üzrə bildirişlər':'Son dakika haberleriyle ilgili bildirimler',
  'Xüsusi günlərlə bağlı bildirişlər':'Özel günlerle ilgili duyurular',
  'Proqram haqqında':'Uygulama hakkında',
  'Müəllif':'Yazar',
  'Qurucu şirkət':'Şirket',
  'Paramterlər': 'Ayarlar',
  'Vayuta məzənnəsi':'Döviz kuru',
  'Hava haqqında':'Hava durumu',
  'Haqqımızda':'Hakkımızda',
  'Bizimlə əlaqə':'İletişim',
  'Mesaj göndərin':'Mesaj gönder',
  'Bizi qiymətləndirin':'Bizi değerlendirin',
  'Məlumatların bazadan çəkilməsi zamanı xəta baş verdi.':'Veritabanından veri alınırken bir hata oluştu.',
  'Məlumat panoya kopyalandı.':'Bilgiler panoya kopyalandı.',
  'Əlaqə telefonu':'Telefon',
  'Elektron poçt':'E-posta',
  'Ünvan':'Adres',
  'İş günləri və saatları':'İş günleri ve saatleri',
  'Sosial şəbəkələr':'Sosyal ağlar',
  'Onlayn mesaj göndərin':'Çevrimiçi mesaj gönderin',
  'Əlavə sual və təkliflərinizlə bağlı aşağıdakı formdan bizə yaza bilərsiniz. Ən qısa zamanda əməkdaşlarımız sizə geri dönüş edəcəklər.':'Ek soru ve önerilerinizi aşağıdaki formu kullanarak bize yazabilirsiniz. Çalışanlarımız en kısa sürede size dönüş yapacaktır.',
  'Ad və soyadınız':'Adınız ve soyadınız',
  'Ad və soyadınızı qeyd etməmisiniz.':'Adınızı ve soyadınızı belirtmemişsiniz.',
  'Email':'E-posta',
  'Email qeyd etməmisiniz.':'Bir e-posta kaydetmediniz.',
  'Mesajınız':'Mesajınız',
  'Heç bir mesaj qeyd etməmisiniz.':'Herhangi bir mesaj kaydetmediniz.',
  'Göndər':'Gönder',
  'Tətbiq daxili xəta baş verdi.':'Dahili bir uygulama hatası oluştu.',
},
};
}